apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gitlab
  name: gitlab
spec:
  containers:
  - image: gitlab/gitlab
    name: gitlab
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
