apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jenkins-pod
    contact: yohan-valette
  name: jenkins-pod
spec:
  containers:
  - image: jenkins/jenkins
    name: jenkins-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
