apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: node
  name: nodejs
spec:
  containers:
  - image: node:lts
    name: nodejs
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
